server:
  port: 10001
  servlet:
    context-path: /user
spring:
  datasource:
    druid:
      filters: stat,slf4j
      web-stat-filter: # WebStatFilter配置
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#      stat-view-servlet: # StatViewServlet配置
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin123
#        login-password: ${v.druid.stat-view-servlet.login-password}
      user:
        url: jdbc:mysql://127.0.0.1:3306/user?useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 10000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 100
        connectProperties:
          connectTimeout: "3000"
          socketTimeout: "30000"

mybatis-plus:
  mapper-locations: com.work.refactor.user.mapper.xml.*